/***
고객 들 중 , 
구매가 없는 고객만 추출해보세요
구매가 있는 고객만 추출해보세요

고객 정보가 기준, 판매 데이터가 옆에 붙으면 됌. 
***/

--구매없는 고객 리스트
SELECT DISTINCT A.MEM_NO
--SELECT *
	FROM MEM A
	LEFT
	JOIN SALES B
	ON A.MEM_NO=B.CUSTOMERID
WHERE B.CUSTOMERID IS NULL

--구매 있는 고객 리스트
SELECT DISTINCT A.MEM_NO
--SELECT *
FROM MEM A
LEFT
JOIN SALES B
ON A.MEM_NO=B.CUSTOMERID
WHERE B.CUSTOMERID IS NOT NULL

/***
고객 들 중 구매가 없는/있는 고객의 수 추출
***/

--구매가 없는 고객의 수
SELECT COUNT(DISTINCT A.MEM_NO) AS NONPUR_CNT --COUNT라는 함수는 집계함수이다.
	FROM MEM A
	LEFT
	JOIN SALES B
	ON A.MEM_NO=B.CUSTOMERID
WHERE B.CUSTOMERID IS NULL

--구매가 있는 고객의 수
SELECT COUNT(DISTINCT A.MEM_NO) AS NONPUR_CNT --COUNT라는 함수는 집계함수이다.
	FROM MEM A
	LEFT
	JOIN SALES B
	ON A.MEM_NO=B.CUSTOMERID
WHERE B.CUSTOMERID IS NOT NULL

/***
고객들 중, 구매가 없는/있는 고객의 수의 비중을 추출하기
***/
SELECT COUNT(DISTINCT A.MEM_NO) AS TOT_CNT
	, COUNT(DISTINCT CASE WHEN B.CUSTOMERID IS NULL THEN A.MEM_NO END) AS NONPUR_CNT --이조건문에는 뒤에 ELSE NULL이 생략되어있음
	, COUNT(DISTINCT CASE WHEN B.CUSTOMERID IS NOT NULL THEN A.MEM_NO END) AS PUR_CNT

	, COUNT(DISTINCT CASE WHEN B.CUSTOMERID IS NULL THEN A.MEM_NO END)*1.00/COUNT(DISTINCT A.MEM_NO)*1.00 AS NONPUR_POR --비중 구하기 공식
	, COUNT(DISTINCT CASE WHEN B.CUSTOMERID IS NOT NULL THEN A.MEM_NO END)*1.00/COUNT(DISTINCT A.MEM_NO)*1.00 AS PUR_POR --1.00으로 나누는것이 중요함.
	FROM MEM A
	LEFT 
	JOIN SALES B
	ON A.MEM_NO=B.CUSTOMERID

/***
고객들의 구매 이력여부(있다/없다) 구분값을 추가해보세요
***/
SELECT MEM_NO --MEM_NO에서 셀렉할건데 아래가 조건
		, CASE WHEN B.CUSTOMERID IS NOT NULL THEN '구매이력_0' --B에서CUSTOMERID가 NULL이 아니면 구매이력_0표시
			   WHEN B.CUSTOMERID IS NULL THEN '구매이력_X' END AS PUR_GB --B에서 CUSTOMERID가 NULL이면 구매이력 X표시

		FROM MEM A --MEM테이블로부터 그리고 걔 이름은 A임
		LEFT --근데 옆에 뭐 붙일거야 그 뭐는 아래코드
		JOIN (
				SELECT DISTINCT CUSTOMERID --SALES테이블에서 CUSTOMERID만 중복안되게 추출
				FROM SALES
		) B --걔이름은  B으로 할거임
		ON A.MEM_NO=B.CUSTOMERID --A의 MEM_NO랑 B의 CUSTOMERID랑 같으면><



