
/***
4강-실습1
고객 ID, 등급 정보(GRADE), 성별정보(GD) 항목을 추출해보세요
***/

SELECT MEM_NO, GRADE, GD
	FROM MEM

/***
4강-실습2
고객 ID, 이름 항목을 추출해보세요
***/

SELECT *
FROM MEM

SELECT MEM_NO,LAST_NAME+FIRST_NAME AS NM
FROM MEM

SELECT MEM_NO,CONCAT(LAST_NAME,FIRST_NAME) AS NM
FROM MEM

/***
4강-실습3
고객 ID, 태어난 연도, 태어난 월, 가입한 연도, 가입한 월 항목을 추출해보세요
각각은 (MEM_NO,DOB_YY,DOB_MM,ENTR_YY,ENTER_MM)
***/

SELECT MEM_NO
	, YEAR(BIRTH_DT) AS DOB_YY
	, MONTH(BIRTH_DT) AS DOB_MM
	, YEAR(ENTR_DT) AS ENTR_YY
	,MONTH(ENTR_DT) AS ENTR_MM
FROM MEM

/***
4강-실습4
고객 ID, 나이 추출
***/

SELECT MEM_NO
	, YEAR(GETDATE())-YEAR(BIRTH_DT)+1 AS AGE /*GETDATA는 현재날짜를 추출해올 수 있는 것*/
	FROM MEM

SELECT MEM_NO
	, DATEDIFF(YEAR,BIRTH_DT,GETDATE())+1 AS AGE /*DATEDIFF는 (뭘 기준으로, 여기를 뺀다, 여기에서)*/
	FROM MEM

	--검증
	SELECT MEM_NO
	,GETDATE()
	,YEAR(GETDATE())
	,BIRTH_DT
	,YEAR(BIRTH_DT) AS YY
	, DATEDIFF(YEAR,BIRTH_DT,GETDATE())+1 AS AGE
	FROM MEM


/***
5강 실습, 실무에서는 우리브랜드의 주연령대를 파악하는데 사용한다. 
이벤트를 기획할 때 고객층을 겨냥해서 기획할 수 있기 떄문!
***/

--CASE WHEN 구문은 조건을 순차적으로 확인한다 
SELECT MEM_NO
	,YEAR(GETDATE())-YEAR(BIRTH_DT)+1 AS AGE
	, CASE WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <10 THEN '10대 미만'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 BETWEEN '10' AND '19' THEN '10대'
	       WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 BETWEEN '20' AND '29' THEN '20대'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 BETWEEN '30' AND '39' THEN '30대'
	       WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 BETWEEN '40' AND '49' THEN '40대'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 BETWEEN '50' AND '59' THEN '50대'
	ELSE 'XX'
	END AS AGEBAND
FROM MEM

SELECT MEM_NO
	,YEAR(GETDATE())-YEAR(BIRTH_DT)+1 AS AGE
	, CASE WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <10 THEN '10대 미만'
	       WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <20 THEN '10대'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <30 THEN '20대'
	       WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <40 THEN '30대'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 <50 THEN '40대'
		   WHEN YEAR(GETDATE())-YEAR(BIRTH_DT)+1 >= 50
				AND YEAR(GETDATE())-YEAR(BIRTH_DT)+1<=100 THEN '50대이상'
	ELSE 'XX' --내가 아는 조건들은 다 WHEN 구문으로 써주고 그래도 모르겠는걸 ELSE에 작성해야 위험도가 줄어들음.
	END AS AGEBAND
FROM MEM


